INSERT INTO CLIENT VALUES(0, 'L','Jemplo');
INSERT INTO CLIENT VALUES(1, 'Keko','Mestio');
INSERT INTO CLIENT VALUES(2, 'Pedro','Duque');
INSERT INTO CLIENT VALUES(3, 'Jose','Martinez');
INSERT INTO CLIENT VALUES(4, 'Arnau','Ramirez');
INSERT INTO CLIENT VALUES(5, 'Joan','Petit');
INSERT INTO CLIENT VALUES(6, 'Elva','Cio');
INSERT INTO CLIENT VALUES(7, 'Lucas','Ruiz');